name = "promplify-web-portal"
compatibility_date = "2024-03-20"

[build]
command = "npm ci && npm run build"
pages_build_output_dir = "dist"

[env.production]
command = "npm ci && npm run build"

[env.preview]
command = "npm ci && npm run build"

[site]
bucket = "./dist"

[build.environment]
NODE_VERSION = "18"
NPM_FLAGS = "--prefer-offline --no-audit" 